project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  description: "A blog built with Quarto"
  site-url: https://aulund.github.io/blog
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aulund
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme:
      - solar
    css: styles.css


